package com.personalassistant.jarvis.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class ConciergePalette(
    val background: Color,
    val surface: Color,
    val surfaceVariant: Color,
    val inputSurface: Color,
    val chip: Color,
    val border: Color,
    val text: Color,
    val mutedText: Color,
    val lightText: Color,
    val onAccent: Color,
    val accent: Color,
    val accentSoft: Color,
    val userBubble: Color,
    val userBubbleText: Color,
    val assistantBubble: Color,
    val assistantBubbleText: Color,
    val voiceGlow: Color,
    val voiceOrb: Color,
    val voiceBackground: Color,
    val danger: Color,
)

val LightPalette = ConciergePalette(
    background = Color(0xFFF6F7F9),
    surface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFFEDEFF1),
    inputSurface = Color(0xFFE3E7EA),
    chip = Color(0xFFE8EAEC),
    border = Color(0xFFE0E3E6),
    text = Color(0xFF151B1D),
    mutedText = Color(0xFF70777D),
    lightText = Color(0xFFB5BBC0),
    onAccent = Color(0xFF0C1216),
    accent = Color(0xFF19D9F4),
    accentSoft = Color(0xFFDDF6F7),
    userBubble = Color(0xFF121B1D),
    userBubbleText = Color(0xFFFFFFFF),
    assistantBubble = Color(0xFFEDEFF1),
    assistantBubbleText = Color(0xFF151B1D),
    voiceGlow = Color(0xFF19D9F4),
    voiceOrb = Color(0xFF121B1D),
    voiceBackground = Color(0xFFE4FBFF),
    danger = Color(0xFFE05656),
)

val DarkPalette = ConciergePalette(
    background = Color(0xFF111417),
    surface = Color(0xFF1A1E22),
    surfaceVariant = Color(0xFF252B2F),
    inputSurface = Color(0xFF2A3035),
    chip = Color(0xFF2D343A),
    border = Color(0xFF2C3137),
    text = Color(0xFFEDEFF1),
    mutedText = Color(0xFFA1AAB0),
    lightText = Color(0xFF6B747B),
    onAccent = Color(0xFF0B1418),
    accent = Color(0xFF7FE7F0),
    accentSoft = Color(0xFF1F3438),
    userBubble = Color(0xFF7FE7F0),
    userBubbleText = Color(0xFF0B1418),
    assistantBubble = Color(0xFF252B2F),
    assistantBubbleText = Color(0xFFEDEFF1),
    voiceGlow = Color(0xFF7FE7F0),
    voiceOrb = Color(0xFFEDEFF1),
    voiceBackground = Color(0xFF14191D),
    danger = Color(0xFFE07A7A),
)

val NeonPalette = ConciergePalette(
    background = Color(0xFF05080D),
    surface = Color(0xFF0A0F16),
    surfaceVariant = Color(0xFF101822),
    inputSurface = Color(0xFF0F1A26),
    chip = Color(0xFF13202E),
    border = Color(0xFF14283A),
    text = Color(0xFFE6FBFF),
    mutedText = Color(0xFF7BA9C2),
    lightText = Color(0xFF3D5C72),
    onAccent = Color(0xFF03161C),
    accent = Color(0xFF19D9F4),
    accentSoft = Color(0xFF0E2B36),
    userBubble = Color(0xFF19D9F4),
    userBubbleText = Color(0xFF03161C),
    assistantBubble = Color(0xFF0F1A26),
    assistantBubbleText = Color(0xFFE6FBFF),
    voiceGlow = Color(0xFF19D9F4),
    voiceOrb = Color(0xFF02161D),
    voiceBackground = Color(0xFF02080D),
    danger = Color(0xFFFF6B81),
)
